#!/usr/bin/env python
"""Aggregate docs/results/results.csv into docs/results/summary.md (mean +- sd over seeds).

    uv run python scripts/summarize.py
"""
from __future__ import annotations

import argparse
from pathlib import Path

import csv
import glob
import json

import numpy as np
import pandas as pd

from boltzmann_fly.paths import RESULTS_CSV, RESULTS_DIR, RUNS_DIR
from boltzmann_fly.pipeline import CSV_COLUMNS


def rebuild_csv(csv_path, runs_dir=RUNS_DIR):
    """results.csv is regenerated from the per-run JSONs (authoritative) so that rows written by older
    processes never lose columns."""
    rows = [json.load(open(f))["row"] for f in sorted(glob.glob(str(runs_dir / "*.json")))]
    with open(csv_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in CSV_COLUMNS})
    return len(rows)

METRICS = [
    ("energy_test_delta_mean", "dF mean (test)"),
    ("energy_test_auc", "AUC clamp (test)"),
    ("energy_test_welch_t", "Welch t hi/lo beta"),
    ("baseline_visit_auc", "MLP visit AUC"),
    ("adapter_visit_full_auc", "Adapter visit AUC"),
    ("baseline_purchase_auc", "MLP purch AUC"),
    ("adapter_purchase_full_auc", "Adapter purch AUC"),
    ("cate_push_visit_gamma", "rho gamma (push->visit)"),
    ("cate_push_visit_alpha", "rho alpha (push->visit)"),
    ("cate_sale1_purchase_alpha", "rho alpha (sale1->purch)"),
    ("cate_sale1_purchase_beta", "rho beta (sale1->purch)"),
    ("belief_sd_median_l1", "belief sd L1 (median)"),
    ("drive_median_l1", "KC drive (median)"),
    ("energy_test_bias_corr", "corr(dF, bias-only)"),
]
PAPER = {  # ICONIP 2026 Table 2/3 and Sec. 4.1 (test split), single seed
    "baseline_visit_auc": 0.7119, "adapter_visit_full_auc": 0.7130, "baseline_purchase_auc": 0.6777,
    "adapter_purchase_full_auc": 0.6772, "cate_push_visit_gamma": 0.625, "cate_push_visit_alpha": -0.148,
    "cate_sale1_purchase_alpha": 0.548, "cate_sale1_purchase_beta": -0.597, "energy_test_delta_mean": 1.07,
    "energy_test_welch_t": -7.66,
}


def fmt(m, s, n):
    if np.isnan(m):
        return "-"
    return f"{m:.3f}" if n <= 1 or np.isnan(s) else f"{m:.3f} ± {s:.3f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", type=Path, default=RESULTS_CSV)
    ap.add_argument("--out", type=Path, default=RESULTS_DIR / "summary.md")
    ap.add_argument("--include-smoke", action="store_true")
    a = ap.parse_args()
    rebuild_csv(a.csv)
    df = pd.read_csv(a.csv)
    if not a.include_smoke:
        df = df[df["smoke"] == 0]
    df["dale"] = df["dale"].astype(int)
    df["tag"] = df["tag"].fillna("").astype(str)
    df["init"] = df["init"].fillna("default").astype(str)
    df["lr_scale"] = df["lr_scale"].fillna(1.0).astype(float)
    df["min_weight"] = pd.to_numeric(df["min_weight"], errors="coerce").fillna(5).astype(int)
    df["n_features_connected"] = pd.to_numeric(df["n_features_connected"], errors="coerce")
    diag_df = df[df["tag"] != ""]
    df = df[df["tag"] == ""]
    grp_cols = ["variant", "control", "dale", "type_select", "init", "lr_scale", "min_weight"]
    lines = ["# Step 1 results summary", "",
             f"Generated by `scripts/summarize.py` from `{a.csv.name}` ({len(df)} runs). Mean ± sd over seeds; "
             "test split. `rho` = Spearman correlation between adapter CATE (logit scale) and the true latent parameter.", ""]
    # header
    cols = ["variant", "control", "dale", "assignment", "w>=", "features in", "init", "lr x", "n seeds", "layers", "belief dim", "couplings", "params"] + [m[1] for m in METRICS] + ["train min (PT+FT)"]
    lines.append("| " + " | ".join(cols) + " |")
    lines.append("|" + "---|" * len(cols))
    # paper reference row
    ref = ["ICONIP paper", "dense", "0", "-", "-", "72", "-", "-", "1", "72-64-32-16", "112", "7,168", "7,352"] + [
        f"{PAPER[m]:.3f}" if m in PAPER else "-" for m, _ in METRICS] + ["~360"]
    lines.append("| " + " | ".join(ref) + " |")
    order = {"V0": 0, "V1": 1, "V1b": 2, "V2": 3}
    corder = {"none": 0, "degree": 1, "er": 2}
    keys = sorted(df.groupby(grp_cols).groups.keys(), key=lambda k: (order.get(k[0], 9), corder.get(k[1], 9), k[2], k[3], k[4], k[5], k[6]))
    for k in keys:
        g = df[(df["variant"] == k[0]) & (df["control"] == k[1]) & (df["dale"] == k[2]) & (df["type_select"] == k[3])
               & (df["init"] == k[4]) & (df["lr_scale"] == k[5]) & (df["min_weight"] == k[6])]
        n = len(g)
        ls = "-".join(str(int(x)) for x in [g["n_visible"].iloc[0], g["n_h1"].iloc[0], g["n_h2"].iloc[0]] + ([g["n_h3"].iloc[0]] if g["n_h3"].iloc[0] else []))
        nfc = g["n_features_connected"].iloc[0]
        cells = [k[0], k[1], str(k[2]), k[3], str(k[6]) if k[0] != "V0" else "-", f"{int(nfc)}/72" if pd.notna(nfc) else "-",
                 k[4], f"{k[5]:g}", str(n), ls, f"{int(g['belief_dim'].iloc[0]):,}",
                 f"{int(g['n_couplings'].iloc[0]):,}", f"{int(g['n_params'].iloc[0]):,}"]
        for m, _ in METRICS:
            cells.append(fmt(g[m].astype(float).mean(), g[m].astype(float).std(ddof=1) if n > 1 else np.nan, n))
        tmin = ((g["t_pretrain_s"].astype(float) + g["t_finetune_s"].astype(float)) / 60)
        cells.append(fmt(tmin.mean(), tmin.std(ddof=1) if n > 1 else np.nan, n))
        lines.append("| " + " | ".join(cells) + " |")
    if len(diag_df):
        lines += ["", "## Diagnostic (tagged) runs: reduced epochs, not part of the main table", "",
                  "| run_id | epochs PT/FT/adapter | belief sd L1 | lowvar L1 | belief sd L2 | KC drive | MBON drive | visit AUC adapter | purchase AUC adapter | rho gamma | rho alpha | corr(dF,bias) |",
                  "|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for _, r in diag_df.sort_values("run_id").iterrows():
            lines.append(f"| {r.run_id} | {int(r.epochs_pt)}/{int(r.epochs_ft)}/{int(r.adapter_epochs)} | {r.belief_sd_median_l1:.3f} | {r.belief_lowvar_frac_l1:.2f} "
                         f"| {r.belief_sd_median_l2:.3f} | {r.drive_median_l1:.2f} | {r.drive_median_l2:.2f} | {r.adapter_visit_full_auc:.4f} | {r.adapter_purchase_full_auc:.4f} "
                         f"| {r.cate_push_visit_gamma:+.3f} | {r.cate_sale1_purchase_alpha:+.3f} | {r.energy_test_bias_corr:.3f} |")
    df = pd.concat([df, diag_df])
    lines += ["", "## Per-run rows", "",
              "| run_id | device | visit AUC (MLP / adapter full / top) | purchase AUC (MLP / full / top) | rho gamma push | rho alpha sale1 | dF test | AUC clamp | PT s | FT s | adapters s | total s |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for _, r in df.sort_values(["variant", "control", "seed"]).iterrows():
        lines.append(f"| {r.run_id} | {r.device} | {r.baseline_visit_auc:.4f} / {r.adapter_visit_full_auc:.4f} / {r.adapter_visit_top_auc:.4f} "
                     f"| {r.baseline_purchase_auc:.4f} / {r.adapter_purchase_full_auc:.4f} / {r.adapter_purchase_top_auc:.4f} "
                     f"| {r.cate_push_visit_gamma:+.3f} | {r.cate_sale1_purchase_alpha:+.3f} | {r.energy_test_delta_mean:+.3f} | {r.energy_test_auc:.3f} "
                     f"| {r.t_pretrain_s:.0f} | {r.t_finetune_s:.0f} | {r.t_adapters_s:.0f} | {r.t_total_s:.0f} |")
    a.out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nwrote {a.out}")


if __name__ == "__main__":
    main()
